### ISSUE TITLE
Selecting videos results in errors

### ISSUE THREAD

**Issue by Aruee** [Ericsson/eva#5]
We're currently evaluating tools to label video data, including eva... however, while we got it running quickly (which was really nice), the tool doesn't do anything when selecting a video but just shows some errors on the cli:

```
[2020-03-09 17:01:12] "POST /upload/testabcde/ HTTP/1.1" 200 73
[2020-03-09 17:01:12] Internal Server Error: /upload/testabcde/done/
Traceback (most recent call last):
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/username/sourcecode/thirdParty/eva/annotator/views.py", line 326, in post
    task = chain(extract_frames.s() | create_cache_task.s())(video.id)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/canvas.py", line 530, in __call__
    return self.apply_async(args, kwargs)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/canvas.py", line 557, in apply_async
    dict(self.options, **options) if options else self.options))
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/canvas.py", line 573, in run
    task_id, group_id, chord,
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/canvas.py", line 666, in prepare_steps
    root_id=root_id, group_id=group_id, chord=chord_body,
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/canvas.py", line 281, in freeze
    return self.AsyncResult(tid)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/task.py", line 749, in AsyncResult
    return self._get_app().AsyncResult(task_id, backend=self.backend,
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/task.py", line 992, in backend
    return self.app.backend
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/base.py", line 1196, in backend
    return self._get_backend()
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/base.py", line 914, in _get_backend
    self.loader)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/backends.py", line 70, in by_url
    return by_name(backend, loader), url
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/app/backends.py", line 50, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/username/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/username/sourcecode/thirdParty/eva/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 22
    from . import async, base
                      ^
SyntaxError: invalid syntax
```

Some system info:

Python 3.7.3
RedHat 7
Linux kernel 3.10.0-1062.12.1.el7.x86_64

**Comment by manishs17** [comment]
Hi @Aruee : try with python 3.6 ( not 3.6.7) . Celery has some issue with 3.7
